<?php

namespace Database\Seeders;

use App\Enums\CapitalTier;
use App\Models\City;
use App\Models\Governorate;
use App\Models\InvestmentCategory;
use App\Models\InvestmentProject;
use App\Models\Machinery;
use Illuminate\Database\Seeder;

class InvestmentProjectSeeder extends Seeder
{
    /**
     * Seed demo investment projects and their machinery requirements.
     */
    public function run(): void
    {
        $technology = InvestmentCategory::where('slug', 'technology')->first();
        $agriculture = InvestmentCategory::where('slug', 'agriculture')->first();
        $industry = InvestmentCategory::where('slug', 'industry')->first();
        $commerce = InvestmentCategory::where('slug', 'commerce')->first();

        $machinery = [
            'laptops' => Machinery::where('name_en', 'Laptop Computers')->first(),
            'solar' => Machinery::where('name_en', 'Solar Panels')->first(),
            'irrigation' => Machinery::where('name_en', 'Irrigation System')->first(),
            'packaging' => Machinery::where('name_en', 'Packaging Machine')->first(),
            'refrigeration' => Machinery::where('name_en', 'Refrigeration Unit')->first(),
            'oven' => Machinery::where('name_en', 'Industrial Oven')->first(),
            'sewing' => Machinery::where('name_en', 'Sewing Machine')->first(),
            'vehicle' => Machinery::where('name_en', 'Delivery Vehicle')->first(),
            'tractor' => Machinery::where('name_en', 'Agricultural Tractor')->first(),
            'line' => Machinery::where('name_en', 'Production Line')->first(),
            'heater' => Machinery::where('name_en', 'Water Heater')->first(),
            'racks' => Machinery::where('name_en', 'Storage Racks')->first(),
        ];

        $projects = [
            // ── Technology ──────────────────────────────────────────────
            [
                'category' => $technology,
                'title_en' => 'Cloud Software Development Studio',
                'title_ar' => 'استوديو تطوير برمجيات سحابية',
                'capital' => 45000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 35,
                'months' => 12,
                'governorate' => 'DM',
                'city' => 'Damascus',
                'quick' => false,
                'machinery' => ['laptops' => 12],
                'lat' => 33.5138,
                'lng' => 36.2765,
            ],
            [
                'category' => $technology,
                'title_en' => 'Mobile Application Development Services',
                'title_ar' => 'خدمات تطوير التطبيقات الذكية',
                'capital' => 25000,
                'tier' => CapitalTier::Small,
                'min' => 25,
                'max' => 40,
                'months' => 9,
                'governorate' => 'AL',
                'city' => 'Aleppo',
                'quick' => true,
                'machinery' => ['laptops' => 8],
                'lat' => 36.2021,
                'lng' => 37.1343,
            ],
            [
                'category' => $technology,
                'title_en' => 'Data Center and Cloud Hosting',
                'title_ar' => 'مركز بيانات واستضافة سحابية',
                'capital' => 250000,
                'tier' => CapitalTier::Large,
                'min' => 15,
                'max' => 25,
                'months' => 24,
                'governorate' => 'DM',
                'city' => 'Barzeh',
                'quick' => false,
                'machinery' => ['laptops' => 20],
                'lat' => 33.5450,
                'lng' => 36.3200,
            ],
            [
                'category' => $technology,
                'title_en' => 'E-Commerce Platform Startup',
                'title_ar' => 'شركة منصة تجارة إلكترونية',
                'capital' => 60000,
                'tier' => CapitalTier::Medium,
                'min' => 22,
                'max' => 38,
                'months' => 10,
                'governorate' => 'LA',
                'city' => 'Latakia',
                'quick' => true,
                'machinery' => ['laptops' => 10, 'vehicle' => 1],
                'lat' => 35.5317,
                'lng' => 35.7901,
            ],
            [
                'category' => $technology,
                'title_en' => 'Cybersecurity Consulting Firm',
                'title_ar' => 'شركة استشارات أمن سيبراني',
                'capital' => 35000,
                'tier' => CapitalTier::Small,
                'min' => 30,
                'max' => 45,
                'months' => 8,
                'governorate' => 'HM',
                'city' => 'Homs',
                'quick' => true,
                'machinery' => ['laptops' => 6],
                'lat' => 34.7308,
                'lng' => 36.7097,
            ],
            [
                'category' => $technology,
                'title_en' => 'Artificial Intelligence R&D Lab',
                'title_ar' => 'مختبر بحث وتطوير ذكاء اصطناعي',
                'capital' => 120000,
                'tier' => CapitalTier::Large,
                'min' => 18,
                'max' => 30,
                'months' => 18,
                'governorate' => 'DM',
                'city' => 'Al-Midan',
                'quick' => false,
                'machinery' => ['laptops' => 15],
                'lat' => 33.5000,
                'lng' => 36.3000,
            ],
            [
                'category' => $technology,
                'title_en' => 'Freelance Digital Marketing Hub',
                'title_ar' => 'مركز تسويق رقمي مستقل',
                'capital' => 15000,
                'tier' => CapitalTier::Small,
                'min' => 28,
                'max' => 42,
                'months' => 6,
                'governorate' => 'HA',
                'city' => 'Hama',
                'quick' => true,
                'machinery' => ['laptops' => 5],
                'lat' => 35.1318,
                'lng' => 36.7578,
            ],
            [
                'category' => $technology,
                'title_en' => 'Fintech Micro-Lending Application',
                'title_ar' => 'تطبيق إقراض صغير تقني مالي',
                'capital' => 80000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 35,
                'months' => 14,
                'governorate' => 'AL',
                'city' => 'Manbij',
                'quick' => false,
                'machinery' => ['laptops' => 9],
                'lat' => 36.5267,
                'lng' => 37.9542,
            ],

            // ── Agriculture ────────────────────────────────────────────
            [
                'category' => $agriculture,
                'title_en' => 'Greenhouse Vegetable Farm',
                'title_ar' => 'مزرعة خضروات في بيوت بلاستيكية',
                'capital' => 55000,
                'tier' => CapitalTier::Medium,
                'min' => 18,
                'max' => 28,
                'months' => 12,
                'governorate' => 'LA',
                'city' => 'Jableh',
                'quick' => false,
                'machinery' => ['irrigation' => 3, 'tractor' => 1],
                'lat' => 35.3625,
                'lng' => 35.9211,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Organic Olive Oil Production',
                'title_ar' => 'إنتاج زيت زيتون عضوي',
                'capital' => 75000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 30,
                'months' => 15,
                'governorate' => 'ID',
                'city' => 'Jisr al-Shughur',
                'quick' => false,
                'machinery' => ['line' => 1, 'packaging' => 1],
                'lat' => 35.8142,
                'lng' => 36.3230,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Modern Poultry Farm',
                'title_ar' => 'مزرعة دواجن حديثة',
                'capital' => 90000,
                'tier' => CapitalTier::Medium,
                'min' => 22,
                'max' => 32,
                'months' => 10,
                'governorate' => 'HM',
                'city' => 'Taldou',
                'quick' => true,
                'machinery' => ['refrigeration' => 2],
                'lat' => 34.8800,
                'lng' => 36.4800,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Drip Irrigation Equipment Supply',
                'title_ar' => 'توريد معدات الري بالتنقيط',
                'capital' => 40000,
                'tier' => CapitalTier::Small,
                'min' => 25,
                'max' => 38,
                'months' => 8,
                'governorate' => 'DR',
                'city' => 'Izra',
                'quick' => true,
                'machinery' => ['irrigation' => 10],
                'lat' => 32.8433,
                'lng' => 36.2511,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Large-Scale Wheat Farm',
                'title_ar' => 'مزرعة قمح واسعة النطاق',
                'capital' => 220000,
                'tier' => CapitalTier::Large,
                'min' => 15,
                'max' => 25,
                'months' => 20,
                'governorate' => 'RA',
                'city' => 'Raqqa',
                'quick' => false,
                'machinery' => ['tractor' => 4, 'irrigation' => 6],
                'lat' => 35.9594,
                'lng' => 38.9981,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Apricot and Fruit Processing',
                'title_ar' => 'تصنيع المشمش والفواكه',
                'capital' => 65000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 30,
                'months' => 12,
                'governorate' => 'HA',
                'city' => 'Salamiyah',
                'quick' => false,
                'machinery' => ['packaging' => 2, 'refrigeration' => 1],
                'lat' => 35.0100,
                'lng' => 37.0500,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Hydroponic Vertical Farm',
                'title_ar' => 'مزرعة عمودية مائية',
                'capital' => 120000,
                'tier' => CapitalTier::Large,
                'min' => 18,
                'max' => 28,
                'months' => 16,
                'governorate' => 'DM',
                'city' => 'Damascus',
                'quick' => false,
                'machinery' => ['irrigation' => 4, 'solar' => 6],
                'lat' => 33.5100,
                'lng' => 36.2900,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Beekeeping and Honey Production',
                'title_ar' => 'تربية النحل وإنتاج العسل',
                'capital' => 20000,
                'tier' => CapitalTier::Small,
                'min' => 30,
                'max' => 45,
                'months' => 7,
                'governorate' => 'SW',
                'city' => 'Shahba',
                'quick' => true,
                'machinery' => ['packaging' => 1],
                'lat' => 32.8527,
                'lng' => 36.6286,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Fish Farming in Mountain Ponds',
                'title_ar' => 'تربية الأسماك في برك جبلية',
                'capital' => 48000,
                'tier' => CapitalTier::Small,
                'min' => 22,
                'max' => 34,
                'months' => 11,
                'governorate' => 'TA',
                'city' => 'Safita',
                'quick' => false,
                'machinery' => ['heater' => 2],
                'lat' => 34.8211,
                'lng' => 36.1175,
            ],
            [
                'category' => $agriculture,
                'title_en' => 'Cotton Cultivation Project',
                'title_ar' => 'مشروع زراعة القطن',
                'capital' => 150000,
                'tier' => CapitalTier::Large,
                'min' => 16,
                'max' => 26,
                'months' => 18,
                'governorate' => 'DZ',
                'city' => 'Al-Mayadin',
                'quick' => false,
                'machinery' => ['tractor' => 3, 'irrigation' => 5],
                'lat' => 35.0200,
                'lng' => 40.4500,
            ],

            // ── Industry ───────────────────────────────────────────────
            [
                'category' => $industry,
                'title_en' => 'Food Packaging Factory',
                'title_ar' => 'مصنع تغليف الأغذية',
                'capital' => 130000,
                'tier' => CapitalTier::Large,
                'min' => 18,
                'max' => 28,
                'months' => 16,
                'governorate' => 'AL',
                'city' => 'Al-Bab',
                'quick' => false,
                'machinery' => ['line' => 1, 'packaging' => 2, 'refrigeration' => 1],
                'lat' => 36.3700,
                'lng' => 37.5200,
            ],
            [
                'category' => $industry,
                'title_en' => 'Confectionery and Sweets Workshop',
                'title_ar' => 'ورشة حلويات ومواد سكرية',
                'capital' => 35000,
                'tier' => CapitalTier::Small,
                'min' => 28,
                'max' => 40,
                'months' => 8,
                'governorate' => 'DM',
                'city' => 'Barzeh',
                'quick' => true,
                'machinery' => ['oven' => 2, 'packaging' => 1],
                'lat' => 33.5400,
                'lng' => 36.3100,
            ],
            [
                'category' => $industry,
                'title_en' => 'Garment and Textile Manufacturing',
                'title_ar' => 'تصنيع الملابس والمنسوجات',
                'capital' => 85000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 32,
                'months' => 14,
                'governorate' => 'HM',
                'city' => 'Al-Qusayr',
                'quick' => false,
                'machinery' => ['sewing' => 12, 'line' => 1],
                'lat' => 34.5078,
                'lng' => 36.5797,
            ],
            [
                'category' => $industry,
                'title_en' => 'Plastic Recycling Plant',
                'title_ar' => 'مصنع إعادة تدوير البلاستيك',
                'capital' => 190000,
                'tier' => CapitalTier::Large,
                'min' => 17,
                'max' => 27,
                'months' => 20,
                'governorate' => 'RD',
                'city' => 'Douma',
                'quick' => false,
                'machinery' => ['line' => 2],
                'lat' => 33.5717,
                'lng' => 36.4017,
            ],
            [
                'category' => $industry,
                'title_en' => 'Bakery and Pastry Production',
                'title_ar' => 'إنتاج المخابز والمعجنات',
                'capital' => 50000,
                'tier' => CapitalTier::Medium,
                'min' => 24,
                'max' => 36,
                'months' => 9,
                'governorate' => 'LA',
                'city' => 'Al-Haffah',
                'quick' => true,
                'machinery' => ['oven' => 3, 'packaging' => 1],
                'lat' => 35.5950,
                'lng' => 36.3150,
            ],
            [
                'category' => $industry,
                'title_en' => 'Furniture Manufacturing Workshop',
                'title_ar' => 'ورشة تصنيع الأثاث',
                'capital' => 62000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 30,
                'months' => 12,
                'governorate' => 'HA',
                'city' => 'Masyaf',
                'quick' => false,
                'machinery' => ['line' => 1, 'racks' => 4],
                'lat' => 35.0650,
                'lng' => 36.3400,
            ],
            [
                'category' => $industry,
                'title_en' => 'Dairy and Cheese Processing',
                'title_ar' => 'تصنيع الألبان والجبن',
                'capital' => 110000,
                'tier' => CapitalTier::Large,
                'min' => 19,
                'max' => 29,
                'months' => 15,
                'governorate' => 'TA',
                'city' => 'Baniyas',
                'quick' => false,
                'machinery' => ['refrigeration' => 3, 'line' => 1],
                'lat' => 35.1820,
                'lng' => 35.9480,
            ],
            [
                'category' => $industry,
                'title_en' => 'Glass and Ceramics Workshop',
                'title_ar' => 'ورشة الزجاج والسيراميك',
                'capital' => 70000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 31,
                'months' => 12,
                'governorate' => 'SW',
                'city' => 'Salkhad',
                'quick' => false,
                'machinery' => ['oven' => 2],
                'lat' => 32.4900,
                'lng' => 36.7100,
            ],
            [
                'category' => $industry,
                'title_en' => 'Soap and Detergent Plant',
                'title_ar' => 'مصنع الصابون والمنظفات',
                'capital' => 45000,
                'tier' => CapitalTier::Small,
                'min' => 26,
                'max' => 38,
                'months' => 10,
                'governorate' => 'AL',
                'city' => 'Aleppo',
                'quick' => true,
                'machinery' => ['line' => 1, 'packaging' => 1],
                'lat' => 36.2000,
                'lng' => 37.1500,
            ],
            [
                'category' => $industry,
                'title_en' => 'Metal Fabrication and Welding',
                'title_ar' => 'تصنيع المعادن واللحام',
                'capital' => 95000,
                'tier' => CapitalTier::Medium,
                'min' => 18,
                'max' => 28,
                'months' => 14,
                'governorate' => 'RD',
                'city' => 'Darayya',
                'quick' => false,
                'machinery' => ['line' => 1],
                'lat' => 33.4583,
                'lng' => 36.2347,
            ],
            [
                'category' => $industry,
                'title_en' => 'Juice and Beverage Production',
                'title_ar' => 'إنتاج العصائر والمشروبات',
                'capital' => 140000,
                'tier' => CapitalTier::Large,
                'min' => 17,
                'max' => 27,
                'months' => 16,
                'governorate' => 'DZ',
                'city' => 'Deir ez-Zor',
                'quick' => false,
                'machinery' => ['line' => 1, 'refrigeration' => 2, 'packaging' => 1],
                'lat' => 35.3359,
                'lng' => 40.1406,
            ],

            // ── Commerce ───────────────────────────────────────────────
            [
                'category' => $commerce,
                'title_en' => 'Grocery Distribution Center',
                'title_ar' => 'مركز توزيع مواد غذائية',
                'capital' => 60000,
                'tier' => CapitalTier::Medium,
                'min' => 22,
                'max' => 34,
                'months' => 10,
                'governorate' => 'DM',
                'city' => 'Damascus',
                'quick' => true,
                'machinery' => ['vehicle' => 3, 'racks' => 6],
                'lat' => 33.5050,
                'lng' => 36.2700,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Online Fashion Retail Store',
                'title_ar' => 'متجر أزياء إلكتروني',
                'capital' => 28000,
                'tier' => CapitalTier::Small,
                'min' => 30,
                'max' => 45,
                'months' => 7,
                'governorate' => 'AL',
                'city' => 'Aleppo',
                'quick' => true,
                'machinery' => ['laptops' => 4, 'racks' => 2],
                'lat' => 36.2100,
                'lng' => 37.1600,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Wholesale Home Appliances Trading',
                'title_ar' => 'تجارة الجملة للأجهزة المنزلية',
                'capital' => 120000,
                'tier' => CapitalTier::Large,
                'min' => 18,
                'max' => 28,
                'months' => 14,
                'governorate' => 'HM',
                'city' => 'Homs',
                'quick' => false,
                'machinery' => ['vehicle' => 2, 'racks' => 8],
                'lat' => 34.7300,
                'lng' => 36.7100,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Pharmaceutical Distribution',
                'title_ar' => 'توزيع الأدوية',
                'capital' => 160000,
                'tier' => CapitalTier::Large,
                'min' => 16,
                'max' => 26,
                'months' => 16,
                'governorate' => 'DM',
                'city' => 'Al-Midan',
                'quick' => false,
                'machinery' => ['refrigeration' => 2, 'vehicle' => 2],
                'lat' => 33.4950,
                'lng' => 36.3050,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Food Truck and Catering Business',
                'title_ar' => 'مطعم متنقل وخدمات طعام',
                'capital' => 22000,
                'tier' => CapitalTier::Small,
                'min' => 32,
                'max' => 48,
                'months' => 6,
                'governorate' => 'LA',
                'city' => 'Latakia',
                'quick' => true,
                'machinery' => ['vehicle' => 1, 'oven' => 1],
                'lat' => 35.5300,
                'lng' => 35.7900,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Agricultural Machinery Trading',
                'title_ar' => 'تجارة الآلات الزراعية',
                'capital' => 90000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 30,
                'months' => 12,
                'governorate' => 'HA',
                'city' => 'Hama',
                'quick' => false,
                'machinery' => ['tractor' => 2, 'racks' => 4],
                'lat' => 35.1300,
                'lng' => 36.7500,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Consumer Electronics Retail Chain',
                'title_ar' => 'سلسلة متاجر الإلكترونيات',
                'capital' => 180000,
                'tier' => CapitalTier::Large,
                'min' => 17,
                'max' => 27,
                'months' => 15,
                'governorate' => 'RD',
                'city' => 'Jaramana',
                'quick' => false,
                'machinery' => ['racks' => 10, 'vehicle' => 2],
                'lat' => 33.4900,
                'lng' => 36.3500,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Organic Produce Market Stand',
                'title_ar' => 'منصة سوق منتجات عضوية',
                'capital' => 18000,
                'tier' => CapitalTier::Small,
                'min' => 30,
                'max' => 44,
                'months' => 7,
                'governorate' => 'TA',
                'city' => 'Tartus',
                'quick' => true,
                'machinery' => ['refrigeration' => 1, 'vehicle' => 1],
                'lat' => 34.8890,
                'lng' => 35.8865,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Logistics and Forwarding Company',
                'title_ar' => 'شركة شحن ولوجستيات',
                'capital' => 250000,
                'tier' => CapitalTier::Large,
                'min' => 15,
                'max' => 25,
                'months' => 20,
                'governorate' => 'AL',
                'city' => 'Manbij',
                'quick' => false,
                'machinery' => ['vehicle' => 5, 'racks' => 8],
                'lat' => 36.5260,
                'lng' => 37.9500,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Perfume and Cosmetics Boutique',
                'title_ar' => 'متجر العطور ومستحضرات التجميل',
                'capital' => 30000,
                'tier' => CapitalTier::Small,
                'min' => 28,
                'max' => 42,
                'months' => 8,
                'governorate' => 'DM',
                'city' => 'Damascus',
                'quick' => true,
                'machinery' => ['racks' => 3],
                'lat' => 33.5120,
                'lng' => 36.2800,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Building Materials Supply Store',
                'title_ar' => 'متجر توريد مواد البناء',
                'capital' => 85000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 30,
                'months' => 12,
                'governorate' => 'DR',
                'city' => 'Daraa',
                'quick' => false,
                'machinery' => ['vehicle' => 2, 'racks' => 6],
                'lat' => 32.6240,
                'lng' => 36.1050,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Mobile Devices and Accessories Wholesale',
                'title_ar' => 'تجارة جملة الأجهزة الذكية وملحقاتها',
                'capital' => 50000,
                'tier' => CapitalTier::Medium,
                'min' => 24,
                'max' => 36,
                'months' => 9,
                'governorate' => 'HS',
                'city' => 'Qamishli',
                'quick' => true,
                'machinery' => ['laptops' => 3, 'racks' => 4],
                'lat' => 37.0521,
                'lng' => 41.2314,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Coffee Roasting and Distribution',
                'title_ar' => 'تحميص القهوة وتوزيعها',
                'capital' => 40000,
                'tier' => CapitalTier::Small,
                'min' => 26,
                'max' => 38,
                'months' => 8,
                'governorate' => 'ID',
                'city' => 'Idlib',
                'quick' => true,
                'machinery' => ['oven' => 2, 'packaging' => 1],
                'lat' => 35.9300,
                'lng' => 36.6300,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Bookstore and Stationery Chain',
                'title_ar' => 'سلسلة مكتبات وقرطاسية',
                'capital' => 55000,
                'tier' => CapitalTier::Medium,
                'min' => 22,
                'max' => 33,
                'months' => 10,
                'governorate' => 'RA',
                'city' => 'Al-Thawrah',
                'quick' => false,
                'machinery' => ['racks' => 5],
                'lat' => 35.8366,
                'lng' => 38.5481,
            ],
            [
                'category' => $commerce,
                'title_en' => 'Auto Parts Distribution',
                'title_ar' => 'توزيع قطع غيار السيارات',
                'capital' => 70000,
                'tier' => CapitalTier::Medium,
                'min' => 20,
                'max' => 30,
                'months' => 11,
                'governorate' => 'SW',
                'city' => 'As-Suwayda',
                'quick' => false,
                'machinery' => ['vehicle' => 2, 'racks' => 5],
                'lat' => 32.7089,
                'lng' => 36.5695,
            ],
        ];

        foreach ($projects as $key => $project) {
            $governorate = Governorate::where('code', $project['governorate'])->first();
            $city = City::where('governorate_id', $governorate?->id)
                ->where('name_en', $project['city'])
                ->first();

            if ($category = $project['category']) {
                $categoryNameEn = $category->name_en;
            } else {
                $categoryNameEn = 'General';
            }

            $projectModel = InvestmentProject::updateOrCreate(
                ['title_en' => $project['title_en']],
                [
                    'investment_category_id' => $category?->id,
                    'governorate_id' => $governorate?->id,
                    'city_id' => $city?->id,
                    'title_ar' => $project['title_ar'],
                    'brief_description_en' => "A {$project['tier']->value}-scale {$categoryNameEn} investment opportunity in {$project['city']}, {$governorate?->name_en}.",
                    'brief_description_ar' => "فرصة استثمارية {$project['tier']->label()} في مجال {$category?->name_ar} في مدينة {$project['city']}, محافظة {$governorate?->name_ar}.",
                    'full_details_en' => "This is a {$project['tier']->label()} investment idea in the {$categoryNameEn} sector located in {$project['city']}, {$governorate?->name_en}. It requires approximately \${$project['capital']} in capital with an expected annual return of {$project['min']}% to {$project['max']}% over a return period of {$project['months']} months.",
                    'full_details_ar' => "هذه فكرة استثمارية {$project['tier']->label()} في قطاع {$category?->name_ar} تقع في مدينة {$project['city']}, محافظة {$governorate?->name_ar}. يتطلب المشروع رأس مال يقارب \${$project['capital']} مع عائد سنوي متوقع يتراوح بين {$project['min']}% و {$project['max']}% على مدى فترة استرداد تبلغ {$project['months']} شهراً.",
                    'required_capital' => $project['capital'],
                    'currency' => 'USD',
                    'capital_tier' => $project['tier'],
                    'expected_profit_rate_min' => $project['min'],
                    'expected_profit_rate_max' => $project['max'],
                    'expected_return_period_months' => $project['months'],
                    'location_description_en' => "Located in {$project['city']}, {$governorate?->name_en}.",
                    'location_description_ar' => "تقع في مدينة {$project['city']}, محافظة {$governorate?->name_ar}.",
                    'latitude' => $project['lat'],
                    'longitude' => $project['lng'],
                    'is_quick_return' => $project['quick'],
                    'is_active' => true,
                ]
            );

            $machineryRows = [];
            foreach ($project['machinery'] as $name => $quantity) {
                if (isset($machinery[$name])) {
                    $machineryRows[$machinery[$name]->id] = ['quantity' => $quantity];
                }
            }

            $projectModel->machinery()->sync($machineryRows);
        }
    }
}
